# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370f061bce6fd324d759f5981c4ed28a8e49ecfb4c323c468894a28c5b9f9ec9fed720d94afb73852edb79a95a23c9e85385aaed334b005b6b6d99c092bcdb82

test:
  secret_key_base: 47c565412be67c8d0d6c531a6552a1123ea713817c5a4c902accac3953488d6c9ec2f3c423a1dd5da40bc7adf9f884e670bd36f2eb1992e67dadf8b57c3b1ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
